steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ev-tracker:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ev-tracker:$SHORT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run', 'deploy', 'ev-tracker',
      '--image', 'gcr.io/$PROJECT_ID/ev-tracker:$SHORT_SHA',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
images:
- 'gcr.io/$PROJECT_ID/ev-tracker:$SHORT_SHA'
